const puzzleList = [
    // [명화 및 예술 - 40개]
    { id: 1, title: "별이 빛나는 밤 (고흐)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1024px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg" },
    { id: 2, title: "키스 (클림트)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/800px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg" },
    { id: 3, title: "모나리자 (다빈치)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa_by_Leonardo_da_Vinci_from_C2RMF_retouched.jpg/800px-Mona_Lisa_by_Leonardo_da_Vinci_from_C2RMF_retouched.jpg" },
    { id: 4, title: "진주 귀걸이를 한 소녀", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Johannes_Vermeer_%281632-1675%29_-_The_Girl_With_The_Pearl_Earring_%281665%29.jpg/800px-Johannes_Vermeer_%281632-1675%29_-_The_Girl_With_The_Pearl_Earring_%281665%29.jpg" },
    { id: 5, title: "절규 (뭉크)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/The_Scream.jpg/800px-The_Scream.jpg" },
    { id: 6, title: "그레이트 웨이브 (호쿠사이)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Great_Wave_off_Kanagawa2.jpg/1024px-Great_Wave_off_Kanagawa2.jpg" },
    { id: 7, title: "비너스의 탄생 (보티첼리)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1024px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg" },
    { id: 8, title: "아담의 창조 (미켈란젤로)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/1024px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg" },
    { id: 9, title: "최후의 만찬 (다빈치)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Ultima_Cena_-_Leonardo_Da_Vinci_-_High_Resolution_Scale_xvaya_2_0_72dpi.jpg/1024px-Ultima_Cena_-_Leonardo_Da_Vinci_-_High_Resolution_Scale_xvaya_2_0_72dpi.jpg" },
    { id: 10, title: "밤의 카페 테라스 (고흐)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Vincent_van_Gogh_-_Cafe_Terrace_at_Night_%28F422%29_-_Google_Art_Project.jpg/800px-Vincent_van_Gogh_-_Cafe_Terrace_at_Night_%28F422%29_-_Google_Art_Project.jpg" },
    { id: 11, title: "양산을 쓴 여인 (모네)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg/800px-Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg" },
    { id: 12, title: "그랑드 자트 섬의 일요일 오후", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/1024px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg" },
    { id: 13, title: "꽃피는 아몬드 나무 (고흐)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Vincent_van_Gogh_-_Almond_blossom_-_Google_Art_Project.jpg/800px-Vincent_van_Gogh_-_Almond_blossom_-_Google_Art_Project.jpg" },
    { id: 14, title: "우유 따르는 여인 (베르메르)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Johannes_Vermeer_-_The_Milkmaid_-_Google_Art_Project.jpg/800px-Johannes_Vermeer_-_The_Milkmaid_-_Google_Art_Project.jpg" },
    { id: 15, title: "수련 (모네)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Claude_Monet_Water_Lilies_1916.jpg/1024px-Claude_Monet_Water_Lilies_1916.jpg" },
    { id: 16, title: "벨라스케스의 시녀들", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg/800px-Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg" },
    { id: 17, title: "바벨탑 (브뢰헬)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project.jpg/1024px-Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project.jpg" },
    { id: 18, title: "인상, 일출 (모네)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/1024px-Monet_-_Impression%2C_Sunrise.jpg" },
    { id: 19, title: "야간 순찰 (렘브란트)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_HD.jpg/1024px-The_Night_Watch_-_HD.jpg" },
    { id: 20, title: "아르놀피니 부부의 초상", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Arnolfini_portrait.jpg/800px-Arnolfini_portrait.jpg" },
    { id: 21, title: "이삭 줍는 사람들 (밀레)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Jean-Fran%C3%A7ois_Millet_-_Des_glaneuses.jpg/1024px-Jean-Fran%C3%A7ois_Millet_-_Des_glaneuses.jpg" },
    { id: 22, title: "해바라기 (고흐)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Vincent_Willem_van_Gogh_127.jpg/800px-Vincent_Willem_van_Gogh_127.jpg" },
    { id: 23, title: "민중을 이끄는 자유의 여신", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eug%C3%A8ne_Delacroix_-_Le_28_juillet._La_Libert%C3%A9_guidant_le_peuple.jpg/1024px-Eug%C3%A8ne_Delacroix_-_Le_28_juillet._La_Libert%C3%A9_guidant_le_peuple.jpg" },
    { id: 24, title: "고대 이집트 투탕카멘 마스크", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Tutankhamun_mask_antwerp.jpg/800px-Tutankhamun_mask_antwerp.jpg" },
    { id: 25, title: "나폴레옹 (알프스를 넘는)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/David_-_Napoleon_at_the_Saint-Bernard_Pass.jpg/800px-David_-_Napoleon_at_the_Saint-Bernard_Pass.jpg" },
    { id: 26, title: "미인도 (신윤복)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Shin_Yun-bok-Miindo.jpg/800px-Shin_Yun-bok-Miindo.jpg" },
    { id: 27, title: "씨름 (김홍도)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Gim_Hong-do-Ssireum.jpg/800px-Gim_Hong-do-Ssireum.jpg" },
    { id: 28, title: "피에타 (미켈란젤로)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Michelangelo%27s_Pieta_5450_cropnblack.jpg/800px-Michelangelo%27s_Pieta_5450_cropnblack.jpg" },
    { id: 29, title: "다비드상", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/David_von_Michelangelo.jpg/800px-David_von_Michelangelo.jpg" },
    { id: 30, title: "밀로의 비너스", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/V%C3%A9nus_de_Milo_-_Mus%C3%A9e_du_Louvre_-_Ma_399_-_n2.jpg/800px-V%C3%A9nus_de_Milo_-_Mus%C3%A9e_du_Louvre_-_Ma_399_-_n2.jpg" },
    { id: 31, title: "니케의 승리상", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Victory_of_Samothrace_Louvre_Ma2369_n4.jpg/800px-Victory_of_Samothrace_Louvre_Ma2369_n4.jpg" },
    { id: 32, title: "생각하는 사람 (로댕)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Le_Penseur_in_the_Mus%C3%A9e_Rodin.jpg/800px-Le_Penseur_in_the_Mus%C3%A9e_Rodin.jpg" },
    { id: 33, title: "반가사유상", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/National_Museum_of_Korea_Pensive_Bodhisattva_Gilt-bronze_Maitreya.jpg/800px-National_Museum_of_Korea_Pensive_Bodhisattva_Gilt-bronze_Maitreya.jpg" },
    { id: 34, title: "신라 금관", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Gold_crown_from_Geumgwanchong.jpg/800px-Gold_crown_from_Geumgwanchong.jpg" },
    { id: 35, title: "달항아리", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Joseon_Moon_Jar.jpg/800px-Joseon_Moon_Jar.jpg" },
    { id: 36, title: "바티칸 천장화", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Sistine_Chapel_ceiling_02.jpg/1024px-Sistine_Chapel_ceiling_02.jpg" },
    { id: 37, title: "카드 놀이하는 사람들", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Les_Joueurs_de_cartes%2C_par_Paul_C%C3%A9zanne.jpg/800px-Les_Joueurs_de_cartes%2C_par_Paul_C%C3%A9zanne.jpg" },
    { id: 38, title: "무대 위의 무용수 (드가)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Edgar_Degas_-_L%27%C3%89toile.jpg/800px-Edgar_Degas_-_L%27%C3%89toile.jpg" },
    { id: 39, title: "아르노 강변의 푸른 풍경", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Claude_Monet_-_Houses_on_the_Acheter_at_Zaandam.jpg/800px-Claude_Monet_-_Houses_on_the_Acheter_at_Zaandam.jpg" },
    { id: 40, title: "고흐의 방", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Vincent_van_Gogh_-_The_Bedroom_-_Google_Art_Project.jpg/800px-Vincent_van_Gogh_-_The_Bedroom_-_Google_Art_Project.jpg" },

    // [랜드마크 및 장소 - 30개]
    { id: 41, title: "에펠탑", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg/800px-Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg" },
    { id: 42, title: "기자의 피라미드", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/All_Gizah_Pyramids.jpg/1024px-All_Gizah_Pyramids.jpg" },
    { id: 43, title: "콜로세움", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Colosseum_in_Rome-Exotic_Holidays_Destination.jpg/800px-Colosseum_in_Rome-Exotic_Holidays_Destination.jpg" },
    { id: 44, title: "타지마할", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Taj_Mahal_%28Edited%29.jpg/800px-Taj_Mahal_%28Edited%29.jpg" },
    { id: 45, title: "자유의 여신상", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Statue_of_Liberty_7.jpg/800px-Statue_of_Liberty_7.jpg" },
    { id: 46, title: "만리장성", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/1024px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg" },
    { id: 47, title: "마추픽추", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/1024px-Machu_Picchu%2C_Peru.jpg" },
    { id: 48, title: "시드니 오페라 하우스", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sydney_Opera_House_Sails.jpg/800px-Sydney_Opera_House_Sails.jpg" },
    { id: 49, title: "피사의 사탑", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Leaning_Tower_of_Pisa.jpg/800px-Leaning_Tower_of_Pisa.jpg" },
    { id: 50, title: "빅 벤 (엘리자베스 타워)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007.jpg/800px-Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007.jpg" },
    { id: 51, title: "경복궁 근정전", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Gyeongbokgung_at_night.jpg/1024px-Gyeongbokgung_at_night.jpg" },
    { id: 52, title: "불국사 다보탑", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Dabotap.jpg/800px-Dabotap.jpg" },
    { id: 53, title: "독도 (대한민국)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Liancourt_Rocks_01.jpg/1024px-Liancourt_Rocks_01.jpg" },
    { id: 54, title: "앙코르 와트", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Angkor_Wat.jpg/1024px-Angkor_Wat.jpg" },
    { id: 55, title: "스톤헨지", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Stonehenge2.jpg/1024px-Stonehenge2.jpg" },
    { id: 56, title: "아야 소피아", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Hagia_Sophia_Mars_2013.jpg/1024px-Hagia_Sophia_Mars_2013.jpg" },
    { id: 57, title: "노이슈반슈타인 성", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Schloss_Neuschwanstein_2013.jpg/1024px-Schloss_Neuschwanstein_2013.jpg" },
    { id: 58, title: "붉은 광장 (모스크바)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Saint_Basil%27s_Cathedral_in_Moscow_August_2023.jpg/800px-Saint_Basil%27s_Cathedral_in_Moscow_August_2023.jpg" },
    { id: 59, title: "금문교", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/GoldenGateBridge-001.jpg/1024px-GoldenGateBridge-001.jpg" },
    { id: 60, title: "부르즈 할리파", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Burj_Khalifa.jpg/800px-Burj_Khalifa.jpg" },
    { id: 61, title: "파르테논 신전", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/The_Parthenon_in_Athens.jpg/1024px-The_Parthenon_in_Athens.jpg" },
    { id: 62, title: "베네치아 운하", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Venice_Canal_Grande_from_Ponte_dell_Accademia.jpg/1024px-Venice_Canal_Grande_from_Ponte_dell_Accademia.jpg" },
    { id: 63, title: "몽생미셸", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Mont_Saint-Michel_at_dawn.jpg/1024px-Mont_Saint-Michel_at_dawn.jpg" },
    { id: 64, title: "산토리니", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Oia_Santorini_at_night.jpg/1024px-Oia_Santorini_at_night.jpg" },
    { id: 65, title: "사그라다 파밀리아", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Sagrada_Familia_01.jpg/800px-Sagrada_Familia_01.jpg" },
    { id: 66, title: "페트라 (카즈네)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Al_Khazne_Petra_Jordan_BW_36.jpg/800px-Al_Khazne_Petra_Jordan_BW_36.jpg" },
    { id: 67, title: "그랜드 캐니언", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Grand_Canyon_view_from_Pima_Point_2010.jpg/1024px-Grand_Canyon_view_from_Pima_Point_2010.jpg" },
    { id: 68, title: "나이아가라 폭포", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Niagara_Falls_Horseshoe_Falls.jpg/1024px-Niagara_Falls_Horseshoe_Falls.jpg" },
    { id: 69, title: "후지 산", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Mount_Fuji_from_Lake_Kawaguchi.jpg/1024px-Mount_Fuji_from_Lake_Kawaguchi.jpg" },
    { id: 70, title: "석굴암 본존불", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Seokguram_Buddha.jpg/800px-Seokguram_Buddha.jpg" },

    // [인물 - 30개]
    { id: 71, title: "세종대왕", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Sejong_the_Great_Portrait.jpg/800px-Sejong_the_Great_Portrait.jpg" },
    { id: 72, title: "이순신 장군", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Yi_Sun-sin_Portrait.jpg/800px-Yi_Sun-sin_Portrait.jpg" },
    { id: 73, title: "알베르트 아인슈타인", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albert_Einstein_Head.jpg/800px-Albert_Einstein_Head.jpg" },
    { id: 74, title: "오드리 헵번", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Audrey_Hepburn_1956.jpg/800px-Audrey_Hepburn_1956.jpg" },
    { id: 75, title: "아브라함 링컨", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Abraham_Lincoln_O-77_by_Gardner%2C_1863-crop.png/800px-Abraham_Lincoln_O-77_by_Gardner%2C_1863-crop.png" },
    { id: 76, title: "나폴레옹 보나파르트", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Napoleon_I_of_France_by_Andrea_Appiani.jpg/800px-Napoleon_I_of_France_by_Andrea_Appiani.jpg" },
    { id: 77, title: "마리 퀴리", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Marie_Curie_1913.jpg/800px-Marie_Curie_1913.jpg" },
    { id: 78, title: "빈센트 반 고흐 (자화상)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg/800px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg" },
    { id: 79, title: "찰리 채플린", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Charlie_Chaplin_portrait.jpg/800px-Charlie_Chaplin_portrait.jpg" },
    { id: 80, title: "베토벤", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Beethoven.jpg/800px-Beethoven.jpg" },
    { id: 81, title: "모차르트", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Wolfgang-amadeus-mozart_1.jpg/800px-Wolfgang-amadeus-mozart_1.jpg" },
    { id: 82, title: "셰익스피어", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Shakespeare.jpg/800px-Shakespeare.jpg" },
    { id: 83, title: "유관순 열사", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Yu_Gwan-sun.jpg/800px-Yu_Gwan-sun.jpg" },
    { id: 84, title: "안중근 의사", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/An_Jung-geun.jpg/800px-An_Jung-geun.jpg" },
    { id: 85, title: "김구 선생님", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Kim_Ku.jpg/800px-Kim_Ku.jpg" },
    { id: 86, title: "윈스턴 처칠", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Sir_Winston_Churchill_1941_Portrait_by_Yousuf_Karsh.jpg/800px-Sir_Winston_Churchill_1941_Portrait_by_Yousuf_Karsh.jpg" },
    { id: 87, title: "마틴 루터 킹", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Martin_Luther_King_Jr_NYWTS.jpg/800px-Martin_Luther_King_Jr_NYWTS.jpg" },
    { id: 88, title: "간디", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Mahatma-Gandhi%2C_studio%2C_1931.jpg/800px-Mahatma-Gandhi%2C_studio%2C_1931.jpg" },
    { id: 89, title: "엘리자베스 1세", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Elizabeth_I_Cornish.jpg/800px-Elizabeth_I_Cornish.jpg" },
    { id: 90, title: "넬슨 만델라", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Nelson_Mandela_1994.jpg/800px-Nelson_Mandela_1994.jpg" },
    { id: 91, title: "아이작 뉴턴", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/GodfreyKneller-IsaacNewton-1689.jpg/800px-GodfreyKneller-IsaacNewton-1689.jpg" },
    { id: 92, title: "갈릴레오 갈릴레이", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Justus_Sustermans_-_Portrait_of_Galileo_Galilei%2C_1636.jpg/800px-Justus_Sustermans_-_Portrait_of_Galileo_Galilei%2C_1636.jpg" },
    { id: 93, title: "공자", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Confucius_02.jpg/800px-Confucius_02.jpg" },
    { id: 94, title: "소크라테스", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Socrates_Louvre.jpg/800px-Socrates_Louvre.jpg" },
    { id: 95, title: "플라톤", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Plato_Pio-Clemetino_Inv305.jpg/800px-Plato_Pio-Clemetino_Inv305.jpg" },
    { id: 96, title: "아리스토텔레스", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Aristotle_Altemps_Inv8575.jpg/800px-Aristotle_Altemps_Inv8575.jpg" },
    { id: 97, title: "프리다 칼로", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg/800px-Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg" },
    { id: 98, title: "신사임당", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Shin_Saimdang.jpg/800px-Shin_Saimdang.jpg" },
    { id: 99, title: "다산 정약용", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Jeong_Yak-yong.jpg/800px-Jeong_Yak-yong.jpg" },
    { id: 100, title: "지구 (우주에서 본)", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/1024px-The_Earth_seen_from_Apollo_17.jpg" }
];
